# Generated by Django 4.0.4 on 2022-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170422_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='cid',
            field=models.CharField(editable=False, max_length=9, unique=True, verbose_name='ID'),
        ),
    ]
