# Generated by Django 4.0.4 on 2022-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170209_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(related_name='group', to='base.contact', verbose_name='contactos'),
        ),
    ]
