# Generated by Django 4.1.3 on 2022-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                ("info", models.CharField(max_length=128, verbose_name="Info")),
            ],
            options={
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "list"),
            },
        ),
    ]
