# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_storages', '0011_merge_20180202_0726'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='zone',
        ),
        migrations.AddField(
            model_name='person',
            name='storage_zone_operables',
            field=models.ManyToManyField(blank=True, null=True, related_name='external', to='codenerix_storages.StorageZone', verbose_name='Storage Zone Operable'),
        ),
    ]
