# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180209_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='storage_zone_operables',
            new_name='storage_zone_operable',
        ),
    ]
