# Generated by Django 4.0.4 on 2022-05-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_geodata', '0003_auto_20180118_1209'),
        ('people', '0004_auto_20180227_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.region', verbose_name='Region'),
        ),
    ]
